### PR TITLE
Documentation: create evalITR website via pkgdown

### PR DESCRIPTION
**Pull request by xiaolong-y**
Hi @MichaelLLi, this is Xiaolong Yang, currently a year 4 undergraduate from UTokyo. Many thanks to Prof. @kosukeimai for this opportunity provided, I will be working on this project to improve the functional versatility of the `evalITR` package, and to improve the documentations etc. I am truly excited to be working together with you. 

This PR sets up the evalITR website via the `pkgdown` package. Detailed development pipeline for the package and progress can be specified and tracked next in github projects/issues of this repo. 

Please let me know if there is any issue or concern with this PR, thanks!

### CODE REVIEW

**Comment by kosukeimai** [comment]
@xiaolong-y Thanks!  This would be fantastic as we discussed!  Let's nail down the structure of the package before you implement. @MichaelLLi We can talk about it too.

**Comment by xiaolong-y** [comment]
@kosukeimai  This sounds great! Currently, there are two unifying approaches of deploying machine learning models in R - `tidymodels` and `mlr3`, which cover the majority of the machine learning methods and packages. One possibility could be to integrate with both, making it straightforward for users from both ecosystems to use our package. I can provide more details on characteristics of both approaches.

**Comment by kosukeimai** [comment]
I think that sounds good, but we also need to incorporate some causality specific ML packages.  Causal Forest, causal BART, double ML, super learner, etc.  For the usual ML packages, it would probably makes sense to have some meta-learner options: X-learner, R-learner, T-learner, etc.

**Comment by MichaelLLi** [comment]
Hi Xiaolong, great to meet you! Echoing Kosuke on need for Causality-specific ML. On a broad basis, we probably want to consider models with X, T, and Y data rather than perhaps just X and Y

**Comment by xiaolong-y** [comment]
@kosukeimai @MichaelLLi  Thanks for the helpful comments, they make a lot of sense! 

I looked into the causal-specific and meta-learner packages and found the following canonical ones:

  - Causality-specific ML: 
    - Causal Forest ([`grf`](https://grf-labs.github.io/grf/))
    - bayesian causal forest ([`bcf`](https://github.com/jaredsmurray/bcf))
    - causal BART ([[`bartMachine`](https://github.com/kapelner/bartMachine), [`dbarts`](https://github.com/vdorie/dbarts) and [`BART`](https://www.jstatsoft.org/article/view/v097i01))
    - double ML ([`DoubleML`](https://github.com/DoubleML/doubleml-for-r))
    - super learner ([`sl3`](https://tlverse.org/sl3/))
    - lasso ([`glmnet`](https://glmnet.stanford.edu/articles/glmnet.html))
  - Meta-learner options: 
    - X-learner ([`causalToolbox`](https://github.com/forestry-labs/causalToolbox))
    - R-learner ([`rlearner`](https://github.com/xnie/rlearner/) which also implements S-, T-, U-, and X-learners)
 - General machine learning frameworks: 
   - [`caret`](https://github.com/topepo/caret)
   - [`SuperLearner`](https://github.com/ecpolley/SuperLearner)
   -  [`mlr3`](https://mlr3.mlr-org.com/) 
   - [`tidymodels`](https://www.tidymodels.org/)
   - [`tlverse`](https://tlverse.org/)
 - Other: 
   - [`GenericML`](https://github.com/mwelz/GenericML) is a package that shares our vision (based on the [Chernozhukov et. al 2020](https://arxiv.org/abs/1712.04802) paper), but mainly relies on the `mlr3` package and does not look versatile enough
   - [`Causal ML`](https://github.com/uber/causalml): a **Python** package that uses Uplift modeling and causal ML methods to estimate CATE and ITE with observational and experimental data. The following is the structure of the package which might provide us with some inspirations. 
   
Screenshot 2022-08-25 at 11 12 58 

I will explore more with these packages while thinking about the structure and good ways to implement changes to our package!

**Comment by kosukeimai** [comment]
Thanks @xiaolong-y !!  I think we should start with Causality-specific ML you listed above.  The design like `CausalML` package makes sense to me if we want to take this to the next level.

**Comment by xiaolong-y** [comment]
@kosukeimai Sounds great! [`grf`](https://grf-labs.github.io/grf/) has amazing documentation and is really widely used. So perhaps I will start from there!

**Pull request closed without merging**
