### PR TITLE
Feat: train under sample splitting (WIP)

### PR DESCRIPTION
**Pull request by xiaolong-y**
This PR now allows users to train the machine learning models under either sample splitting or cross validation by setting the argument `n_folds` in `run_itr`. Please set `n_folds = 0` to enable training under sample splitting. Please see this [updated readme](https://github.com/xiaolong-y/evalITR/tree/causal-ml-gate) for more details. 

@jialul This code is still undergoing tests so it would be great if you could try running latest functions on your machine to test run. Thank you! In the meantime, I will clean up the codes and work on the documentations.

### CODE REVIEW

**Comment by jialul** [comment]
Thanks @xiaolong-y! Can you update your changes to the `causal-ml-gates` branch you created earlier within Michael's `evalITR` repo. It seems that the changes you make current stay in your personal branch, which I cannot pull from it.

**Comment by jialul** [comment]
Also, by eyeballing your code, I think you may want to write them in the package format. For example, new inputs like `ratio` needs to be documented and functions you called from other packages need to be imported before running your own function. Kosuke recommended [this book](https://r-pkgs.org/) when I started formatting the code. Guess you may find it helpful!

**Comment by xiaolong-y** [comment]
@jialul Thank you for your response! Since this code is still experimental, I thought merging after cleaning up and testing will be prefered. You can still download the code of this PR using devtools by inputting `devtools::install_github("MichaelLLi/evalITR#21")`. Please let me know if you run into any issue. 

Thank you for the suggestion and I will look into it!

**Comment by jialul** [comment]
No need to worry about merging or conflicts. What you've done on `causal-ml-gates` will not affect either the `master` or `causal-ml`. Please update your changes to `causal-ml-gates` so that I can pull from that branch, thanks!

**Pull request merged**
